version: '3'
services:
  url_short:
    build: tools
    user: 1000:1000
    ports:
      - "80:80"
    volumes:
      #- ./vanilla-app:/var/www/html
      - ./laravel-app:/var/www/html
    command: >
      bash -c "apache2-foreground"
